version: '3'
services:
  db:
    image: mysql:8.0.33
    #command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Admin123
    expose:
      - 3306
  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db.cdjoh3mr89uq.us-east-1.rds.amazonaws.com
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=Admin123
      - WORDPRESS_DB_NAME=testdb
volumes:
  db_data:
  wp_data:


